CREATE TABLE IF NOT EXISTS customers(
    id BIGINT(50) AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL ,
    last_name VARCHAR(100)  NOT NULL ,
    address VARCHAR(100)  NOT NULL ,
    budget DECIMAL(50) NOT NULL

);